# This file was generated by GoReleaser. DO NOT EDIT.
class PipelineCli < Formula
  desc "SIGHUP Pipeline CLI"
  homepage "https://github.com/sighupio/pipeline-cli"
  version "0.1.0-rc13"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sighupio/pipeline-cli/releases/download/v0.1.0-rc13/sighup-pipeline-darwin-amd64.tar.gz"
    sha256 "dba46ac1ddac9ad25e3c3bc335bd8029be5f802a43238f309460fe90b56aa239"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/pipeline-cli/releases/download/v0.1.0-rc13/sighup-pipeline-linux-amd64.tar.gz"
      sha256 "004b7e3136ae92f5315e580525c50114b5250a0dca10f7ee951c156f5d8abbd4"
    end
  end
  
  conflicts_with "sighup-pipeline"

  def install
    bin.install 'sighup-pipeline'
  end

  test do
    system "#{bin}/sighup-pipeline"
  end
end
