# This file was generated by GoReleaser. DO NOT EDIT.
class PipelineCli < Formula
  desc "SIGHUP Pipeline CLI"
  homepage "https://github.com/sighupio/pipeline-cli"
  version "0.1.0-rc12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sighupio/pipeline-cli/releases/download/v0.1.0-rc12/sighup-pipeline-darwin-amd64.tar.gz"
    sha256 "dd5e512729bfde6a0faf0dfc5f397c395ebfc506bfc4f62c7d87ff150ff539fd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/pipeline-cli/releases/download/v0.1.0-rc12/sighup-pipeline-linux-amd64.tar.gz"
      sha256 "2f3c73b5ad5f6d544990748907fe1e0bd899ce42c800c8cf88777e65a8b9e70f"
    end
  end
  
  conflicts_with "sighup-pipeline"

  def install
    bin.install 'sighup-pipeline'
  end

  test do
    system "#{bin}/sighup-pipeline"
  end
end
